export type ShopCategory =
  | "All"
  | "Connect"
  | "Power"
  | "Store & Protect"
  | "Work Anywhere";

export type ShopItem = {
  slug: string;
  category: Exclude<ShopCategory, "All">;
  subcategory: string;
  name: string;
  tagline: string;
  badge?: string;
  priceDisplay: string;
  availabilityStatus: string;
  description: string;
  bestFor: string;
  whyCanodRecommends: string;
  compatibility: string[];
  specifications: { label: string; value: string }[];
  canadianInformation: string;
  guideSlug?: string;
  guideTitle?: string;
  toolPath?: string;
  toolTitle?: string;
  relatedProductSlugs?: string[];
};

export const shopCategories: ShopCategory[] = [
  "All",
  "Connect",
  "Power",
  "Store & Protect",
  "Work Anywhere",
];

export const shopCategoryDescriptions: Record<Exclude<ShopCategory, "All">, {
  summary: string;
  subcategories: string[];
}> = {
  Connect: {
    summary: "Cables, adapters, hubs, docks, and networking gear that link computers, displays, and devices without signal dropouts or bandwidth bottlenecks.",
    subcategories: [
      "USB-C Cables",
      "HDMI & Display Cables",
      "Adapters",
      "USB-C Hubs",
      "Docking Stations",
      "Wi-Fi & Networking",
    ],
  },
  Power: {
    summary: "GaN chargers, laptop power supplies, CATSA-compliant power banks, and heavy-duty Canadian surge protection vetted for electrical safety.",
    subcategories: [
      "USB-C Chargers",
      "GaN Chargers",
      "Laptop Chargers",
      "Power Banks",
      "Charging Cables",
      "Travel Power",
    ],
  },
  "Store & Protect": {
    summary: "Rugged SSDs, storage enclosures, clamshell pouches, and padded sleeves designed to safeguard hardware and personal data.",
    subcategories: [
      "Tech Organizers",
      "Laptop Sleeves",
      "Cable Organizers",
      "SSD / Drive Cases",
      "Travel Cases",
    ],
  },
  "Work Anywhere": {
    summary: "Ergonomic stands, monitor arms, cable channels, and mobile desk accessories engineered for productive hybrid and remote work.",
    subcategories: [
      "Laptop Stands",
      "Portable Monitors",
      "Hubs & Docks",
      "Travel Accessories",
      "Desk Accessories",
      "Mobile Work Essentials",
    ],
  },
};

export const shopItems: ShopItem[] = [
  // --- CONNECT ---
  {
    slug: "tb4-dual-display-dock",
    category: "Connect",
    subcategory: "Docking Stations",
    name: "Thunderbolt 4 / USB4 Dual Display Dock",
    tagline: "Uncompromised dual 4K monitor support and 96W host laptop charging.",
    badge: "Workstation Grade",
    priceDisplay: "Check Canadian Retailers",
    availabilityStatus: "In Stock at Canadian authorized tech distributors",
    description: "Designed for demanding workstations requiring dual external displays, high-speed peripherals, and single-cable charging. Delivers true 40 Gbps bandwidth across macOS and Windows systems.",
    bestFor: "Professionals and creators connecting two 4K screens, high-speed storage, and Gigabit Ethernet to a MacBook Pro or Windows workstation.",
    whyCanodRecommends: "Unlike budget USB-C hubs that compress video over DisplayLink drivers, this hardware uses native Thunderbolt/DisplayPort tunneling for zero display lag and full 96W charging headroom.",
    compatibility: [
      "Apple Silicon Macs (M1/M2/M3/M4 Pro and Max support dual extended displays; base M1/M2/M3 support single display)",
      "Windows laptops with Thunderbolt 4, Thunderbolt 3, or full-featured USB4",
      "Dual displays up to 4K @ 60Hz or single 8K @ 30Hz",
    ],
    specifications: [
      { label: "Upstream Bandwidth", value: "40 Gbps Thunderbolt 4 / USB4" },
      { label: "Host Power Delivery", value: "96W continuous USB Power Delivery" },
      { label: "Display Outputs", value: "2x Thunderbolt 4 down-facing / HDMI 2.1" },
      { label: "Networking", value: "Gigabit Ethernet RJ45 port" },
      { label: "Audio & Media", value: "UHS-II SD 4.0 card slot, 3.5mm combo audio" },
    ],
    canadianInformation: "Supplied with North American 120V AC power adapter bearing CSA or cUL electrical certification. Meets Canadian Energy Efficiency regulations.",
    guideSlug: "seven-things-usb-c-dock",
    guideTitle: "7 Things to Check Before Buying a USB-C Dock",
    toolPath: "/tools/usb-c-dock-checker/",
    toolTitle: "Verify Setup in Dock Compatibility Checker",
    relatedProductSlugs: ["certified-40gbps-tb4-cable", "dual-gas-spring-monitor-arm", "under-desk-cable-tray"],
  },
  {
    slug: "compact-travel-usb-c-hub",
    category: "Connect",
    subcategory: "USB-C Hubs",
    name: "7-in-1 Aluminum USB-C Travel Hub",
    tagline: "Lightweight multi-port connectivity for hybrid and remote work.",
    badge: "Everyday Carry",
    priceDisplay: "Check Canadian Retailers",
    availabilityStatus: "Available across Canadian retail partners",
    description: "Essential workstation ports housed in a precision-milled aluminum chassis. Provides 4K 60Hz HDMI video, 100W Power Delivery pass-through, dual USB-A 3.2 ports, and micro/SD card readers.",
    bestFor: "Hybrid workers, consultants, and travelers needing to plug into conference room projectors, USB drives, and monitors on the go.",
    whyCanodRecommends: "Provides true 4K @ 60Hz output (when connected to DisplayPort 1.4 hosts) instead of the choppy 30Hz refresh rate common in entry-level hubs.",
    compatibility: [
      "USB-C laptops supporting DisplayPort Alternate Mode (MacBook, Dell XPS, Lenovo ThinkPad, Surface)",
      "iPad Pro and USB-C tablets",
      "Windows, macOS, ChromeOS, and Linux",
    ],
    specifications: [
      { label: "Video Output", value: "HDMI 2.0 (4K @ 60Hz on DP 1.4 hosts; 4K @ 30Hz on DP 1.2)" },
      { label: "Power Pass-Through", value: "100W USB-C PD input (reserves ~15W for hub operation)" },
      { label: "USB Data Ports", value: "2x USB-A 3.2 Gen 2 (10 Gbps transfer speed)" },
      { label: "Card Reader", value: "MicroSD and SD UHS-I (up to 104 MB/s)" },
    ],
    canadianInformation: "Aluminum body provides passive heat dissipation suitable for variable Canadian room temperatures. Backed by Canadian retailer return policies.",
    guideSlug: "seven-things-usb-c-dock",
    guideTitle: "USB-C Hub & Display Compatibility Guide",
    toolPath: "/tools/usb-c-dock-checker/",
    toolTitle: "Check Laptop Video & Hub Capabilities",
    relatedProductSlugs: ["tb4-dual-display-dock", "expandable-clamshell-tech-pouch"],
  },
  {
    slug: "certified-40gbps-tb4-cable",
    category: "Connect",
    subcategory: "USB-C Cables",
    name: "Certified 40 Gbps Thunderbolt 4 Cable (0.8m)",
    tagline: "High-bandwidth single-cable connection for docks, eGPUs, and 8K displays.",
    badge: "Thunderbolt Certified",
    priceDisplay: "Check Canadian Retailers",
    availabilityStatus: "In Stock",
    description: "Official Intel-certified Thunderbolt 4 cable supporting full 40 Gbps bidirectional transfer, 100W Power Delivery, and dual 4K / single 8K video output. Reinforced strain relief prevents connector fraying.",
    bestFor: "Connecting a laptop to a Thunderbolt 4 dock, high-speed external NVMe RAID enclosure, or studio display.",
    whyCanodRecommends: "Guarantees full 40 Gbps throughput without signal attenuation. Passive 0.8m length maintains complete compatibility with USB4, USB 3.2, and USB 2.0 protocols.",
    compatibility: [
      "Thunderbolt 4, Thunderbolt 3, and USB4 ports",
      "Backwards compatible with USB-C 3.2, 3.1, and 2.0",
      "Supports 100W USB Power Delivery",
    ],
    specifications: [
      { label: "Data Rate", value: "40 Gbps bidirectional" },
      { label: "Power Delivery", value: "100W (20V / 5A) EPR supported" },
      { label: "Length", value: "0.8 meters (2.6 feet)" },
      { label: "Connector", value: "USB Type-C with stamped lightning bolt logo" },
    ],
    canadianInformation: "Meets ISED Canada electromagnetic interference limits (ICES-003 Class B) for clean domestic operation without radio interference.",
    guideSlug: "why-usb-c-cables-work-differently",
    guideTitle: "Why USB-C Cables Work Differently",
    toolPath: "/tools/usb-c-dock-checker/",
    toolTitle: "Check Port & Cable Capabilities",
    relatedProductSlugs: ["tb4-dual-display-dock", "compact-travel-usb-c-hub"],
  },
  {
    slug: "cat6-solid-copper-patch-cable",
    category: "Connect",
    subcategory: "Wi-Fi & Networking",
    name: "Cat6 Snagless Pure Copper Ethernet Cable (15ft)",
    tagline: "Low-latency Gigabit and 2.5 GbE wired connection for docks, NAS, and gaming.",
    badge: "Pure Copper 24AWG",
    priceDisplay: "Check Canadian Retailers",
    availabilityStatus: "In Stock",
    description: "Constructed with 100% bare copper conductors (not cheap Copper Clad Aluminum / CCA). Delivers reliable 1 Gbps / 2.5 Gbps / 10 Gbps speeds with minimal packet loss and zero Wi-Fi interference.",
    bestFor: "Connecting a docking station, home NAS, or desktop PC to your router or wall jack for lag-free video calls and fast backups.",
    whyCanodRecommends: "Avoids the brittle conductors and fire hazards of Copper Clad Aluminum (CCA). Real 24 AWG annealed copper maintains signal integrity over distance.",
    compatibility: [
      "RJ45 Gigabit, 2.5 GbE, and 10 GbE network interfaces",
      "Compatible with Cat5e and Cat6a hardware",
      "Supports Power over Ethernet (PoE / PoE+)",
    ],
    specifications: [
      { label: "Conductor Material", value: "100% Bare Stranded Copper (24 AWG)" },
      { label: "Bandwidth", value: "550 MHz frequency rating" },
      { label: "Jacket", value: "CM-rated PVC with snagless molded boot" },
      { label: "Length", value: "15 feet (4.57 meters)" },
    ],
    canadianInformation: "Complies with Canadian Electrical Code standards for low-voltage communications patch cabling.",
    guideSlug: "wifi-slow-in-one-room",
    guideTitle: "Why is My Wi-Fi Slow in One Room?",
    toolPath: "/tools/usb-c-dock-checker/",
    toolTitle: "Check Dock & Networking Hardware",
    relatedProductSlugs: ["tb4-dual-display-dock", "rugged-portable-nvme-ssd"],
  },

  // --- POWER ---
  {
    slug: "gan-100w-multiport-charger",
    category: "Power",
    subcategory: "GaN Chargers",
    name: "100W GaN Fast Wall Charger (2x USB-C + 1x USB-A)",
    tagline: "High-efficiency gallium nitride power brick for laptop and phone simultaneously.",
    badge: "cUL / CSA Certified",
    priceDisplay: "Check Canadian Retailers",
    availabilityStatus: "Available in Canada with full warranty",
    description: "Replaces multiple bulky factory power bricks. Uses Gallium Nitride (GaN) semiconductors to operate cooler and smaller while providing dynamic smart power allocation across 3 devices.",
    bestFor: "Professionals who want one compact charger for a 65W/96W laptop, phone, and tablet at home or while traveling.",
    whyCanodRecommends: "Features verified North American electrical safety certification marks (cUL or CSA) and intelligent PPS power profiles that negotiate safe charging voltages.",
    compatibility: [
      "USB-C Power Delivery 3.0 / PPS for MacBooks, Dell, Lenovo, HP, Surface",
      "Fast charging for iPhone, Samsung Galaxy, and Google Pixel",
      "Single port: 100W Max; Dual port: 65W + 30W smart split",
    ],
    specifications: [
      { label: "Total Wattage", value: "100W Max output" },
      { label: "Ports", value: "2x USB-C (PD 3.0 / PPS) + 1x USB-A (QC 3.0)" },
      { label: "Semiconductor", value: "GaN (Gallium Nitride) III" },
      { label: "Prongs", value: "Foldable standard North American 2-prong AC" },
    ],
    canadianInformation: "Certified for Canadian 120V / 60Hz mains supply with authentic cUL / CSA mark. Safe for continuous residential and commercial use.",
    guideSlug: "charger-safety-canada",
    guideTitle: "Buy Safe in Canada: Charger Safety Checks",
    toolPath: "/tools/canadian-electrical-safety-checklist/",
    toolTitle: "Run Charger Safety Inspection",
    relatedProductSlugs: ["certified-240w-usb-c-cable", "airline-approved-power-bank", "expandable-clamshell-tech-pouch"],
  },
  {
    slug: "airline-approved-power-bank",
    category: "Power",
    subcategory: "Power Banks",
    name: "20,000 mAh (74 Wh) 65W USB-C Power Bank",
    tagline: "Laptop-capable portable power pack fully compliant with CATSA airline thresholds.",
    badge: "CATSA Compliant (74 Wh)",
    priceDisplay: "Check Canadian Retailers",
    availabilityStatus: "In Stock at Canadian retailers",
    description: "Delivers full 65W output to power laptops, tablets, and phones on the go. Its 74 Watt-hour capacity stays safely below CATSA's strict 100 Wh carry-on limit for passenger flights.",
    bestFor: "Commuters, travelers, and remote workers who need reliable emergency power away from wall outlets without airport security confiscation risks.",
    whyCanodRecommends: "Clearly and permanently displays the 74 Wh rating on its exterior casing, preventing airport security confiscation. Supplies 65W output to keep modern laptops powered under load.",
    compatibility: [
      "Laptops requiring 45W, 60W, or 65W USB-PD charging",
      "iPads, tablets, Nintendo Switch, and Steam Deck",
      "Smartphones with fast USB-C PD or PPS charging",
    ],
    specifications: [
      { label: "Rated Capacity", value: "20,000 mAh @ 3.7V (74 Watt-hours)" },
      { label: "USB-C Output", value: "65W Max (20V/3.25A, 15V/3A, 9V/3A, 5V/3A)" },
      { label: "USB-C Recharging", value: "Up to 65W input (recharges in ~2 hours)" },
      { label: "Protection", value: "Overcurrent, overvoltage, over-temperature, short-circuit" },
    ],
    canadianInformation: "Meets CATSA and Transport Canada criteria for carry-on passenger lithium-ion batteries under 100 Wh. Must be packed in carry-on luggage, never checked baggage.",
    guideSlug: "what-size-power-bank-do-i-need",
    guideTitle: "What Size Power Bank Do I Need?",
    toolPath: "/tools/canadian-electrical-safety-checklist/",
    toolTitle: "Check Battery Safety Standards",
    relatedProductSlugs: ["gan-100w-multiport-charger", "certified-240w-usb-c-cable"],
  },
  {
    slug: "certified-240w-usb-c-cable",
    category: "Power",
    subcategory: "Charging Cables",
    name: "Certified USB-IF 240W USB-C EPR Cable (2m)",
    tagline: "High-wattage Extended Power Range cable with E-Marker protection silicon.",
    badge: "USB-IF Certified",
    priceDisplay: "Check Canadian Retailers",
    availabilityStatus: "In Stock",
    description: "Engineered for safe high-wattage charging up to 48V / 5A (240W). Built with reinforced double-braided nylon and an integrated E-Marker microchip that safely negotiates power with the charger.",
    bestFor: "Powering laptops, high-draw monitors, and power banks from 65W to 240W over a durable, long 2-meter span.",
    whyCanodRecommends: "Prevents cable overheating and socket damage. Complies strictly with USB-IF Extended Power Range (EPR) specifications for high-draw hardware.",
    compatibility: [
      "USB-C Power Delivery 3.1 Extended Power Range (EPR) up to 240W",
      "Backwards compatible with 60W, 100W, and 140W USB-C chargers",
      "USB 2.0 (480 Mbps) data sync (charging-optimized cable)",
    ],
    specifications: [
      { label: "Maximum Power", value: "240W (48V / 5A EPR)" },
      { label: "E-Marker Chip", value: "Integrated certified USB-IF safety controller" },
      { label: "Length", value: "2.0 meters (6.6 feet)" },
      { label: "Durability", value: "Tested to 25,000+ 90-degree bend cycles" },
    ],
    canadianInformation: "Constructed with flame-retardant internal TPE insulation conforming to Canadian electrical safety best practices.",
    guideSlug: "why-usb-c-cables-work-differently",
    guideTitle: "Why USB-C Cables Work Differently",
    toolPath: "/tools/canadian-electrical-safety-checklist/",
    toolTitle: "Verify Cable Safety & Voltage",
    relatedProductSlugs: ["gan-100w-multiport-charger", "airline-approved-power-bank"],
  },
  {
    slug: "heavy-duty-surge-protector",
    category: "Power",
    subcategory: "Travel Power",
    name: "8-Outlet Canadian Surge Protector (14 AWG / 2160J)",
    tagline: "Certified surge suppression and clean power distribution for home offices.",
    badge: "cUL / CSA Approved",
    priceDisplay: "Check Canadian Retailers",
    availabilityStatus: "Widely available in Canada",
    description: "Features heavy-duty 14 AWG pure copper conductors, 2,160 Joules of MOV surge absorption, a 15A thermal circuit breaker, and widely spaced transformer outlets.",
    bestFor: "Protecting computer workstations, monitors, network gear, and audio equipment from voltage spikes and lightning transients.",
    whyCanodRecommends: "Uses genuine 14 AWG copper wire capable of handling continuous 15-amp loads (1,875W) safely without dangerous wire heating. Includes genuine Canadian safety approval.",
    compatibility: [
      "Standard Canadian 120V / 15A grounded wall outlets",
      "Accommodates up to 8 AC plugs (including 3 oversized transformer bricks)",
      "Integrated dual USB-A charging ports (2.4A)",
    ],
    specifications: [
      { label: "Surge Energy Rating", value: "2,160 Joules" },
      { label: "Cord Gauge", value: "14 AWG heavy-duty pure copper (6 feet)" },
      { label: "Electrical Rating", value: "125V AC / 15A / 1875W Max" },
      { label: "Circuit Breaker", value: "15A thermal reset switch" },
    ],
    canadianInformation: "Certified by an SCC-accredited testing body (cUL, CSA, or cETL). Verifiable on provincial electrical safety registries like the Ontario ESA.",
    guideSlug: "power-bar-or-surge-protector-canada",
    guideTitle: "Power Bar or Surge Protector: What Should Canadians Check?",
    toolPath: "/tools/canadian-electrical-safety-checklist/",
    toolTitle: "Inspect Surge Bar in Safety Checklist",
    relatedProductSlugs: ["under-desk-cable-tray", "gan-100w-multiport-charger"],
  },

  // --- STORE & PROTECT ---
  {
    slug: "expandable-clamshell-tech-pouch",
    category: "Store & Protect",
    subcategory: "Tech Organizers",
    name: "Weatherproof Clamshell Tech Organizer Pouch (2.5L)",
    tagline: "Origami-style internal divider pockets keep chargers, cables, and adapters organized.",
    badge: "Everyday Carry",
    priceDisplay: "Check Canadian Retailers",
    availabilityStatus: "In Stock at Canadian outdoor and carry retailers",
    description: "Opens wide in an accordion clamshell layout on any desk or airplane tray. Recycled weatherproof canvas shell keeps sensitive accessories dry and scratch-free.",
    bestFor: "Anyone tired of untangling cords at the bottom of a backpack or moving accessories between work and home bags.",
    whyCanodRecommends: "Its structured origami layout allows the pouch to stand upright on a desk, making cables and memory cards visible without unpacking everything.",
    compatibility: [
      "Fits standard 65W-100W GaN chargers, mice, and 20,000mAh power banks",
      "Elastic loops securely hold cables, pens, and flash drives",
      "Pass-through charging port allows charging while closed",
    ],
    specifications: [
      { label: "Capacity", value: "2.5 Liters" },
      { label: "Shell Material", value: "Weatherproof 100% recycled nylon canvas (DWR impregnated)" },
      { label: "Pockets", value: "12 internal dividers + zippered security pocket" },
      { label: "Dimensions", value: "24 cm x 15 cm x 10 cm (0.29 kg)" },
    ],
    canadianInformation: "Designed to endure Canadian winter commutes and wet weather with heavy-duty weatherproof reverse-coil zippers.",
    guideSlug: "choosing-a-tech-organizer",
    guideTitle: "Choosing a Tech Organizer: Size, Layout & Daily Use",
    toolPath: "/tools/usb-c-dock-checker/",
    toolTitle: "Check What Gear You Need to Carry",
    relatedProductSlugs: ["gan-100w-multiport-charger", "airline-approved-power-bank", "water-resistant-laptop-sleeve"],
  },
  {
    slug: "water-resistant-laptop-sleeve",
    category: "Store & Protect",
    subcategory: "Laptop Sleeves",
    name: "Magnetic Closure Padded Laptop Sleeve with Accessory Pocket",
    tagline: "Slim, protective padded sleeve with 360-degree edge cushioning.",
    badge: "Premium Protection",
    priceDisplay: "Check Canadian Retailers",
    availabilityStatus: "In Stock",
    description: "Shields your laptop from impact and weather. Features high-density edge bumpers, soft microfleece lining, and a convenient front zippered pocket for slim cables and adapters.",
    bestFor: "Safeguarding 13-14\" and 15-16\" laptops inside tote bags, backpacks, or carried standalone.",
    whyCanodRecommends: "Reinforced corner and edge padding protects where laptops are most vulnerable to drops, while the magnetic flap closure avoids scratch-prone zipper teeth.",
    compatibility: [
      "Available in 13-14\" size (MacBook Pro 14, Dell XPS 13/14, ThinkPad X1)",
      "Available in 15-16\" size (MacBook Pro 16, Dell XPS 15/16)",
    ],
    specifications: [
      { label: "Exterior", value: "Water-resistant textured recycled polyester" },
      { label: "Interior", value: "Thick plush microfleece scratch protection" },
      { label: "Closure", value: "Quiet magnetic seal + auxiliary zippered pocket" },
      { label: "Edge Protection", value: "Reinforced 360-degree impact foam perimeter" },
    ],
    canadianInformation: "Durable water-repellent fabric sheds snow and rain during Canadian daily transit.",
    guideSlug: "choosing-a-tech-organizer",
    guideTitle: "Everyday Carry & Tech Organization",
    relatedProductSlugs: ["expandable-clamshell-tech-pouch", "aluminum-ergonomic-laptop-stand"],
  },
  {
    slug: "rugged-portable-nvme-ssd",
    category: "Store & Protect",
    subcategory: "SSD / Drive Cases",
    name: "Rugged 2TB USB 3.2 Gen 2x2 Portable NVMe SSD",
    tagline: "Ultra-fast 2000 MB/s solid-state drive for Time Machine and local backups.",
    badge: "2000 MB/s NVMe",
    priceDisplay: "Check Canadian Retailers",
    availabilityStatus: "Available at Canadian electronics retailers",
    description: "Drop-resistant and IP55 water-resistant portable solid-state drive. Features hardware-accelerated 256-bit AES encryption to keep personal data and work files secure.",
    bestFor: "Serving as the primary local backup destination for macOS Time Machine or Windows File History, or offloading 4K video footage.",
    whyCanodRecommends: "Solid-state storage has no moving parts to break during transit. High sustained write speeds allow complete system backups in minutes instead of hours.",
    compatibility: [
      "USB 3.2 Gen 2x2 (20 Gbps) for full 2,000 MB/s speed",
      "USB 3.2 Gen 2 (10 Gbps) at ~1,050 MB/s speed",
      "macOS (APFS / HFS+), Windows (NTFS / exFAT), Linux, Android, iPadOS",
    ],
    specifications: [
      { label: "Read / Write Speed", value: "Up to 2,000 MB/s read, 2,000 MB/s write" },
      { label: "Interface", value: "USB 3.2 Gen 2x2 Type-C" },
      { label: "Durability Rating", value: "IP55 water/dust resistance, 3m drop protection" },
      { label: "Encryption", value: "Password-enabled 256-bit AES hardware encryption" },
    ],
    canadianInformation: "Sold with full 5-year Canadian warranty coverage through authorized national distributors.",
    guideSlug: "how-much-backup-storage",
    guideTitle: "How Much Backup Storage Do I Need?",
    toolPath: "/tools/canadian-electrical-safety-checklist/",
    toolTitle: "Check Power & Hardware Ratings",
    relatedProductSlugs: ["hard-drive-eva-travel-case", "certified-40gbps-tb4-cable"],
  },
  {
    slug: "hard-drive-eva-travel-case",
    category: "Store & Protect",
    subcategory: "Travel Cases",
    name: "Molded EVA Shockproof External Drive Case",
    tagline: "Rigid protective travel case for portable SSDs, cables, and flash drives.",
    badge: "Shockproof EVA",
    priceDisplay: "Check Canadian Retailers",
    availabilityStatus: "In Stock",
    description: "Semi-rigid molded EVA shell lined with soft velvet. Includes an elastic retaining strap for the drive and an internal mesh pouch for USB cables and thumb drives.",
    bestFor: "Protecting portable SSDs and mechanical hard drives from being crushed, dropped, or scratched inside a laptop bag.",
    whyCanodRecommends: "A low-cost investment that prevents physical port damage and drive degradation caused by impact during commuting.",
    compatibility: [
      "Fits standard 2.5\" portable hard drives and external SSDs",
      "Interior dimensions: 13.5 cm x 9.0 cm x 3.5 cm",
    ],
    specifications: [
      { label: "Material", value: "High-density molded EVA foam shell" },
      { label: "Interior", value: "Shock-absorbing velvet lining + elastic restraint" },
      { label: "Zipper", value: "Heavy-duty dual metal slider" },
    ],
    canadianInformation: "Ships directly across Canada via national fulfillment channels.",
    guideSlug: "how-much-backup-storage",
    guideTitle: "Backing Up Important Files Safely",
    relatedProductSlugs: ["rugged-portable-nvme-ssd", "expandable-clamshell-tech-pouch"],
  },

  // --- WORK ANYWHERE ---
  {
    slug: "dual-gas-spring-monitor-arm",
    category: "Work Anywhere",
    subcategory: "Desk Accessories",
    name: "Dual Gas-Spring Heavy-Duty Monitor Arm (VESA 75/100)",
    tagline: "Ergonomic dual-display positioning with internal cable routing channels.",
    badge: "Ergonomic Setup",
    priceDisplay: "Check Canadian Retailers",
    availabilityStatus: "In Stock across Canada",
    description: "Counterbalanced gas-spring arms support two displays up to 32 inches each (19.8 lbs per arm). Features full 360-degree rotation, tilt, swivel, and integrated cable concealment.",
    bestFor: "Freeing up desk surface, eliminating neck strain, and creating a clean dual-display workstation layout.",
    whyCanodRecommends: "Smooth gas-spring tension holds screens firmly in position without drooping. Hidden cable cavities keep HDMI and DisplayPort cords invisible.",
    compatibility: [
      "VESA 75x75mm and 100x100mm mounting patterns",
      "Screens from 17\" up to 32\" (up to 19.8 lbs / 9 kg per monitor)",
      "Desk thickness: 10mm to 85mm (C-clamp or grommet mount)",
    ],
    specifications: [
      { label: "Arm Mechanism", value: "Adjustable gas-spring counterbalance" },
      { label: "Adjustment Range", value: "+90°/-45° tilt, 180° swivel, 360° rotation" },
      { label: "Max Height Extension", value: "41 cm (16.1 inches) from desk" },
      { label: "Material", value: "Aircraft-grade aluminum and heavy steel base" },
    ],
    canadianInformation: "Compatible with standard solid Canadian desks. Note: not recommended for hollow honeycomb core tables without reinforcing plates.",
    guideSlug: "seven-things-usb-c-dock",
    guideTitle: "Multi-Monitor Fit & Workstation Setup",
    toolPath: "/tools/usb-c-dock-checker/",
    toolTitle: "Check Monitor Resolution & Dock Bandwidth",
    relatedProductSlugs: ["tb4-dual-display-dock", "under-desk-cable-tray"],
  },
  {
    slug: "aluminum-ergonomic-laptop-stand",
    category: "Work Anywhere",
    subcategory: "Laptop Stands",
    name: "Foldable Ventilated Aluminum Laptop Stand",
    tagline: "Elevates laptop screens to eye level to improve posture and cooling airflow.",
    badge: "Ergonomic Fit",
    priceDisplay: "Check Canadian Retailers",
    availabilityStatus: "In Stock",
    description: "CNC-anodized aluminum riser with multi-angle height adjustment. Elevates your laptop screen to eye level, reducing neck hunching while maximizing convective airflow under the chassis.",
    bestFor: "Remote workers and desk setups using a laptop alongside an external keyboard and mouse or dual screens.",
    whyCanodRecommends: "Solid aluminum construction prevents wobbling during typing. Open cooling cutouts prevent laptop thermal throttling under heavy processor loads.",
    compatibility: [
      "Fits all laptops from 10\" to 17\" (MacBook, ThinkPad, Dell XPS, HP, Asus)",
      "Supports loads up to 10 kg (22 lbs)",
    ],
    specifications: [
      { label: "Material", value: "Solid 4mm sandblasted aluminum alloy" },
      { label: "Height Adjustment", value: "6 angle steps (5.5 cm to 15.5 cm elevation)" },
      { label: "Pads", value: "Non-slip anti-scratch silicone contact pads" },
      { label: "Folded Profile", value: "Folds flat to 1.5 cm for transport" },
    ],
    canadianInformation: "Durable aluminum construction built for long-term daily use without mechanical degradation.",
    guideSlug: "choosing-a-tech-organizer",
    guideTitle: "Portable Work Setup Considerations",
    relatedProductSlugs: ["tb4-dual-display-dock", "compact-travel-usb-c-hub"],
  },
  {
    slug: "under-desk-cable-tray",
    category: "Work Anywhere",
    subcategory: "Desk Accessories",
    name: "Heavy-Duty Under-Desk Cable Management Channel",
    tagline: "Keeps power bricks, surge bars, and excess cables off the floor.",
    badge: "Clean Desk",
    priceDisplay: "Check Canadian Retailers",
    availabilityStatus: "In Stock",
    description: "Steel wire mesh tray that clamps securely beneath fixed or sit-stand desks without drilling. Holds full-size 8-outlet surge bars, dock power supplies, and cable slack.",
    bestFor: "Standing desk owners and home office setups seeking a clean, uncluttered aesthetic and easy floor vacuuming.",
    whyCanodRecommends: "Open-wire design prevents heat buildup from AC transformers and dock power bricks, unlike enclosed plastic trays that trap heat.",
    compatibility: [
      "Fits desks with thickness from 1.0 cm to 5.0 cm",
      "Clamps without drilling or damaging wood finishes",
    ],
    specifications: [
      { label: "Dimensions", value: "43 cm length x 15 cm width x 12 cm depth" },
      { label: "Weight Capacity", value: "Up to 10 kg (22 lbs) of power gear" },
      { label: "Material", value: "Powder-coated heavy steel wire" },
    ],
    canadianInformation: "Standard Canadian residential desk mounting hardware included.",
    guideSlug: "power-bar-or-surge-protector-canada",
    guideTitle: "Power Bar & Surge Protection Setup",
    toolPath: "/tools/canadian-electrical-safety-checklist/",
    toolTitle: "Check Electrical Cord Safety",
    relatedProductSlugs: ["heavy-duty-surge-protector", "dual-gas-spring-monitor-arm"],
  },
  {
    slug: "compact-travel-dock-pouch-kit",
    category: "Work Anywhere",
    subcategory: "Mobile Work Essentials",
    name: "Hybrid Commuter Dock & Cable Kit",
    tagline: "Curated travel hub, certified EPR cable, and organizer pouch for hybrid workers.",
    badge: "Curated Bundle",
    priceDisplay: "Check Canadian Retailers",
    availabilityStatus: "Curated Canadian Reference Kit",
    description: "A pre-matched mobile workstation bundle combining our recommended 7-in-1 USB-C hub, certified 100W GaN charger, and clamshell pouch. Built so you never leave an adapter behind.",
    bestFor: "Hybrid professionals alternating between home offices, coworking desks, and corporate headquarters.",
    whyCanodRecommends: "Every component is verified to work together: the charger provides enough wattage to power both the laptop and the hub's HDMI display port without power drops.",
    compatibility: [
      "Universal for MacBook, Windows laptops, and USB-C tablets",
      "Provides HDMI 4K video, USB ports, and 100W charging",
    ],
    specifications: [
      { label: "Includes", value: "7-in-1 Travel Hub, 100W GaN Wall Charger, Clamshell Pouch" },
      { label: "Total Carry Weight", value: "Under 550 grams combined" },
    ],
    canadianInformation: "All electrical components carry legitimate Canadian approvals (cUL or CSA).",
    guideSlug: "choosing-a-tech-organizer",
    guideTitle: "Everyday Carry & Travel Gear Guide",
    toolPath: "/tools/usb-c-dock-checker/",
    toolTitle: "Verify Hub & Cable Pairing",
    relatedProductSlugs: ["compact-travel-usb-c-hub", "gan-100w-multiport-charger", "expandable-clamshell-tech-pouch"],
  },
];
