import type { Metadata } from "next";
import { ArrowRight } from "lucide-react";
export const metadata: Metadata = { title: "For Brands" };
export default function PartnersPage() { return <>
  <section className="page-hero"><div className="site-container"><p className="eyebrow page-kicker">For brands</p><h1 className="page-title">Grow carefully in Canada.</h1></div></section>
  <section className="section-space bg-paper"><div className="site-container grid gap-14 lg:grid-cols-[.55fr_1.45fr]"><p className="eyebrow text-maple">A retail relationship</p><div><p className="prose-large max-w-5xl">CANOD is interested in building direct wholesale relationships with select Canadian and North American brands that value a careful, brand-consistent ecommerce presence.</p><p className="mt-10 max-w-3xl text-lg leading-8 text-ink/65">We are especially interested in useful, well-designed products for work, travel, organization, and everyday life. Our initial focus is the Canadian market, including Amazon.ca and other appropriate online channels.</p></div></div></section>
  <section className="section-space bg-white"><div className="site-container"><p className="eyebrow text-maple">What we value</p><div className="mt-12 grid gap-10 md:grid-cols-2 lg:grid-cols-4">{[["01","Clear authorization","Direct, documented relationships that protect the brand and customer."],["02","Careful presentation","Accurate product content and a marketplace presence aligned with brand standards."],["03","Reliable inventory","Measured purchasing, responsible forecasting, and straightforward communication."],["04","Long-term fit","A sustainable retail relationship—not a race to the lowest price."]].map(([n,title,copy]) => <article className="rule-card" key={n}><p className="number">{n}</p><h2 className="mt-9 text-xl font-semibold tracking-[-.03em]">{title}</h2><p className="mt-4 text-sm leading-7 text-ink/65">{copy}</p></article>)}</div></div></section>
  <section className="section-space bg-navy text-white"><div className="site-container grid gap-10 lg:grid-cols-[1.3fr_.7fr] lg:items-end"><div><p className="eyebrow text-white/45">Start a conversation</p><h2 className="mt-6 text-[clamp(2.8rem,6vw,6rem)] font-semibold leading-[.95] tracking-[-.055em]">Could CANOD be a fit for your brand?</h2></div><a className="button button-light w-fit lg:justify-self-end" href="mailto:hello@canod.ca?subject=Brand%20partnership%20with%20CANOD">Email hello@canod.ca <ArrowRight size={17} /></a></div></section>
  </>; }
